### ISSUE TITLE
Moving camera while mouse is over object causes scene to shake

### ISSUE THREAD

**Issue by k9** [mustafasaifee42/VR-Viz#8]
In non-VR (just on my macbook screen with Chrome), when I have my mouse over the object on https://vr-viz.netlify.com/?selectedKind=Cross-section%20View&selectedStory=Cross-section%20View&full=0&addons=1&stories=1&panelRight=1&addonPanel=kadira%2Fjsx%2Fpanel and I move using WASD, the scene shakes back and forth.

**Comment by mustafasaifee42** [comment]
This is mainly because the older version of vr-viz was not optimized.  Now with the updated version it should work better as it is more optimized. 

Also since this demo page has a lot of a-frame scenes for different graphs thats why it causes a lot of memory over loading. For this reason there might be some issue with the loading of some scenes also and finding the pivot point for rotation for example in the case of TreeMap and dashboard
